name: Process Diary Queue

on:
  push:
    paths:
      - '_queue/*.json'
  workflow_dispatch:

jobs:
  process-diary:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml pytz
    
    - name: Process diary queue
      run: |
        python scripts/process_diary_queue.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action (Diary Queue)"
        git add .
        if git diff --staged --quiet; then
          echo "変更がありません"
        else
          git commit -m "📝 日記キューを処理: $(date '+%Y-%m-%d %H:%M')"
          git push
        fi
